CC = m68k-amigaos-gcc
AR = m68k-amigaos-ar

CFLAGS = -g -O0 -Wall -Wextra -std=c99 -m68020
CPPFLAGS = -Iinclude

OBJS = \
	src/libromm.amiga.o \
	src/minijson.amiga.o \
	src/transport_amiga.amiga.o \
	examples/romm_amiga.amiga.o

.PHONY: all clean

all: romm-amiga

romm-amiga: $(OBJS)
	$(CC) $(CFLAGS) -o $@ $(OBJS)

src/libromm.amiga.o: src/libromm.c
	$(CC) $(CPPFLAGS) $(CFLAGS) -c $< -o $@

src/minijson.amiga.o: src/minijson.c
	$(CC) $(CPPFLAGS) $(CFLAGS) -c $< -o $@

src/transport_amiga.amiga.o: src/transport_amiga.c
	$(CC) $(CPPFLAGS) $(CFLAGS) -c $< -o $@

examples/romm_amiga.amiga.o: examples/romm_amiga.c
	$(CC) $(CPPFLAGS) $(CFLAGS) -c $< -o $@

clean:
	rm -f \
		src/*.amiga.o \
		examples/*.amiga.o \
		romm-amiga
